
export const memoryGameData = [
    { id: 1, word: 'Apple', icon: <span role="img" aria-label="Apple" className="text-4xl md:text-5xl">🍎</span> },
    { id: 2, word: 'Car', icon: <span role="img" aria-label="Car" className="text-4xl md:text-5xl">🚗</span> },
    { id: 3, word: 'Dog', icon: <span role="img" aria-label="Dog" className="text-4xl md:text-5xl">🐕</span> },
    { id: 4, word: 'Cat', icon: <span role="img" aria-label="Cat" className="text-4xl md:text-5xl">🐈</span> },
    { id: 5, word: 'Home', icon: <span role="img" aria-label="Home" className="text-4xl md:text-5xl">🏠</span> },
    { id: 6, word: 'Book', icon: <span role="img" aria-label="Book" className="text-4xl md:text-5xl">📖</span> },
    { id: 7, word: 'Tree', icon: <span role="img" aria-label="Tree" className="text-4xl md:text-5xl">🌳</span> },
    { id: 8, word: 'Sun', icon: <span role="img" aria-label="Sun" className="text-4xl md:text-5xl">☀️</span> },
    { id: 9, word: 'Moon', icon: <span role="img" aria-label="Moon" className="text-4xl md:text-5xl">🌙</span> },
    { id: 10, word: 'Star', icon: <span role="img" aria-label="Star" className="text-4xl md:text-5xl">⭐</span> },
    { id: 11, word: 'Bike', icon: <span role="img" aria-label="Bike" className="text-4xl md:text-5xl">🚲</span> },
    { id: 12, word: 'Bus', icon: <span role="img" aria-label="Bus" className="text-4xl md:text-5xl">🚌</span> },
    { id: 13, word: 'Train', icon: <span role="img" aria-label="Train" className="text-4xl md:text-5xl">🚆</span> },
    { id: 14, word: 'Plane', icon: <span role="img" aria-label="Plane" className="text-4xl md:text-5xl">✈️</span> },
    { id: 15, word: 'Boat', icon: <span role="img" aria-label="Boat" className="text-4xl md:text-5xl">🚤</span> },
    { id: 16, word: 'Flower', icon: <span role="img" aria-label="Flower" className="text-4xl md:text-5xl">🌸</span> },
    { id: 17, word: 'Bird', icon: <span role="img" aria-label="Bird" className="text-4xl md:text-5xl">🐦</span> },
    { id: 18, word: 'Fish', icon: <span role="img" aria-label="Fish" className="text-4xl md:text-5xl">🐟</span> },
    { id: 19, word: 'Lion', icon: <span role="img" aria-label="Lion" className="text-4xl md:text-5xl">🦁</span> },
    { id: 20, word: 'Tiger', icon: <span role="img" aria-label="Tiger" className="text-4xl md:text-5xl">🐯</span> },
    { id: 21, word: 'Bear', icon: <span role="img" aria-label="Bear" className="text-4xl md:text-5xl">🐻</span> },
    { id: 22, word: 'Elephant', icon: <span role="img" aria-label="Elephant" className="text-4xl md:text-5xl">🐘</span> },
    { id: 23, word: 'Monkey', icon: <span role="img" aria-label="Monkey" className="text-4xl md:text-5xl">🐒</span> },
    { id: 24, word: 'Cow', icon: <span role="img" aria-label="Cow" className="text-4xl md:text-5xl">🐮</span> },
    { id: 25, word: 'Giraffe', icon: <span role="img" aria-label="Giraffe" className="text-4xl md:text-5xl">🦒</span> },
    { id: 26, word: 'Sheep', icon: <span role="img" aria-label="Sheep" className="text-4xl md:text-5xl">🐑</span> },
    { id: 27, word: 'Horse', icon: <span role="img" aria-label="Horse" className="text-4xl md:text-5xl">🐴</span> },
    { id: 28, word: 'Duck', icon: <span role="img" aria-label="Duck" className="text-4xl md:text-5xl">🦆</span> },
    { id: 29, word: 'Chicken', icon: <span role="img" aria-label="Chicken" className="text-4xl md:text-5xl">🐔</span> },
    { id: 30, word: 'Pizza', icon: <span role="img" aria-label="Pizza" className="text-4xl md:text-5xl">🍕</span> },
    { id: 31, word: 'Burger', icon: <span role="img" aria-label="Burger" className="text-4xl md:text-5xl">🍔</span> },
    { id: 32, word: 'Ice Cream', icon: <span role="img" aria-label="Ice Cream" className="text-4xl md:text-5xl">🍦</span> },
    { id: 33, word: 'Cake', icon: <span role="img" aria-label="Cake" className="text-4xl md:text-5xl">🍰</span> },
    { id: 34, word: 'Water', icon: <span role="img" aria-label="Water" className="text-4xl md:text-5xl">💧</span> },
    { id: 35, word: 'Milk', icon: <span role="img" aria-label="Milk" className="text-4xl md:text-5xl">🥛</span> },
    { id: 36, word: 'Juice', icon: <span role="img" aria-label="Juice" className="text-4xl md:text-5xl">🧃</span> },
];
