import { Briefcase, Coffee, GraduationCap, Plane, Stethoscope } from "lucide-react";

// --- Data (Full Database Restored) ---
const MOCK_DB = {
  user: {
    name: "אורח",
    xp: 0,
    streak: 1,
    level: 1,
    darkMode: true
  },
  lessons: [
    {
      id: 1,
      title: "יסודות",
      icon: "🌱",
      color: "bg-green-500",
      totalQuestions: 10,
      words: [
        { id: 1, en: "Hello", he: "שלום", options: ["שלום", "תודה", "להתראות", "בוקר"] },
        { id: 2, en: "Thank you", he: "תודה", options: ["סליחה", "בבקשה", "תודה", "כן"] },
        { id: 3, en: "Yes", he: "כן", options: ["לא", "כן", "אולי", "מחר"] },
        { id: 4, en: "No", he: "לא", options: ["כן", "תמיד", "לא", "לפעמים"] },
        { id: 5, en: "Good morning", he: "בוקר טוב", options: ["לילה טוב", "ערב טוב", "בוקר טוב", "יום טוב"] },
        { id: 106, en: "Please", he: "בבקשה", options: ["תודה", "בבקשה", "סליחה", "שלום"] },
        { id: 107, en: "Sorry", he: "סליחה", options: ["בבקשה", "סליחה", "תודה", "שלום"] },
        { id: 108, en: "Goodbye", he: "להתראות", options: ["שלום", "להתראות", "בוקר", "לילה"] },
        { id: 109, en: "Help", he: "עזרה", options: ["עזרה", "משפחה", "חבר", "בית"] },
        { id: 110, en: "Friend", he: "חבר", options: ["מורה", "חבר", "בן משפחה", "שכן"] },
      ]
    },
    {
      id: 2,
      title: "אוכל ושתייה",
      icon: "🍎",
      color: "bg-orange-500",
      totalQuestions: 10,
      words: [
        { id: 6, en: "Apple", he: "תפוח", options: ["תפוז", "תפוח", "בננה", "אגס"] },
        { id: 7, en: "Water", he: "מים", options: ["לחם", "יין", "מים", "חלב"] },
        { id: 8, en: "Bread", he: "לחם", options: ["לחם", "חמאה", "גבינה", "ביצה"] },
        { id: 9, en: "Coffee", he: "קפה", options: ["תה", "מיץ", "קפה", "שוקו"] },
        { id: 10, en: "Chicken", he: "עוף", options: ["בקר", "דג", "עוף", "הכבש"] },
        { id: 111, en: "Milk", he: "חלב", options: ["חלב", "מים", "מיץ", "יין"] },
        { id: 112, en: "Juice", he: "מיץ", options: ["קולה", "מיץ", "חלב", "שייק"] },
        { id: 113, en: "Cheese", he: "גבינה", options: ["גבינה", "לחם", "חלב", "ביצה"] },
        { id: 114, en: "Egg", he: "ביצה", options: ["ביצה", "לחם", "חמאה", "גבינה"] },
        { id: 115, en: "Tomato", he: "עגבניה", options: ["מלון", "עגבניה", "תפוח", "בננה"] },
      ]
    },
    {
      id: 3,
      title: "נסיעות",
      icon: "✈️",
      color: "bg-blue-500",
      totalQuestions: 10,
      words: [
        { id: 11, en: "Hotel", he: "מלון", options: ["בית", "מלון", "מסעדה", "חנות"] },
        { id: 12, en: "Ticket", he: "כרטיס", options: ["דרכון", "מזוודה", "כרטיס", "מפה"] },
        { id: 116, en: "Train", he: "רכבת", options: ["אוטו", "אוטובוס", "רכבת", "סירה"] },
        { id: 117, en: "Taxi", he: "מונית", options: ["אופניים", "מונית", "רכבת", "אוטובוס"] },
        { id: 118, en: "Airport", he: "שדה תעופה", options: ["נמל", "תחנה", "שדה תעופה", "נמל תעופה"] },
        { id: 119, en: "Passport", he: "דרכון", options: ["תעודה", "דרכון", "כרטיס", "רישיון"] },
        { id: 120, en: "Luggage", he: "מזוודה", options: ["מזוודה", "תרמיל", "תיק", "שק"] },
        { id: 121, en: "Station", he: "תחנה", options: ["תחנה", "שדה", "מגרש", "בית"] },
        { id: 122, en: "Map", he: "מפה", options: ["מפה", "מדריך", "מחשב", "טלפון"] },
        { id: 123, en: "Ticket office", he: "משרד כרטיסים", options: ["קופה", "משרד", "שירות", "משרד כרטיסים"] },
      ]
    }
    ,
    {
      id: 4,
      title: "צבעים",
      icon: "🎨",
      color: "bg-red-400",
      totalQuestions: 10,
      words: [
        { id: 13, en: "Red", he: "אדום", options: ["אדום", "כחול", "ירוק", "צהוב"] },
        { id: 14, en: "Blue", he: "כחול", options: ["לבן", "כחול", "שחור", "חום"] },
        { id: 15, en: "Yellow", he: "צהוב", options: ["וורוד", "סגול", "צהוב", "אפור"] },
        { id: 64, en: "Green", he: "ירוק", options: ["ירוק", "סגול", "כחול", "חום"] },
        { id: 65, en: "Black", he: "שחור", options: ["לבן", "שחור", "צהוב", "כחול"] },
        { id: 66, en: "White", he: "לבן", options: ["שחור", "לבן", "ורוד", "אפור"] },
        { id: 67, en: "Purple", he: "סגול", options: ["סגול", "חום", "ירוק", "שחור"] },
        { id: 68, en: "Orange", he: "כתום", options: ["כתום", "כחול", "ירוק", "אדום"] },
        { id: 69, en: "Brown", he: "חום", options: ["סגול", "חום", "כחול", "שחור"] },
        { id: 70, en: "Pink", he: "ורוד", options: ["ורוד", "צהוב", "שחור", "לבן"] },
      ]
    },
    {
      id: 5,
      title: "צורות",
      icon: "🔺",
      color: "bg-yellow-400",
      totalQuestions: 10,
      words: [
        { id: 16, en: "Circle", he: "עגול", options: ["מרובע", "משולש", "עגול", "מלבן"] },
        { id: 17, en: "Square", he: "מרובע", options: ["מרובע", "עגול", "לב", "כוכב"] },
        { id: 18, en: "Triangle", he: "משולש", options: ["משולש", "אליפסה", "קו", "נקודה"] },
        { id: 71, en: "Rectangle", he: "מלבן", options: ["מלבן", "עגול", "מרובע", "לב"] },
        { id: 72, en: "Oval", he: "ביצה/אליפסה", options: ["אליפסה", "משולש", "עגול", "כוכב"] },
        { id: 73, en: "Star", he: "כוכב", options: ["לב", "כוכב", "עגול", "משולש"] },
        { id: 74, en: "Heart", he: "לב", options: ["לב", "מגן", "כדור", "משולש"] },
        { id: 75, en: "Diamond", he: "יהלום", options: ["מרובע", "יהלום", "עגול", "לב"] },
        { id: 76, en: "Pentagon", he: "מחומש", options: ["משולש", "מחומש", "עגול", "מלבן"] },
        { id: 77, en: "Hexagon", he: "משושה", options: ["משושה", "עגול", "מרובע", "לב"] },
      ]
    },
    {
      id: 6,
      title: "חיות",
      icon: "🐶",
      color: "bg-green-400",
      totalQuestions: 10,
      words: [
        { id: 19, en: "Dog", he: "כלב", options: ["כלב", "חתול", "תנין", "סוס"] },
        { id: 20, en: "Cat", he: "חתול", options: ["פרה", "חתול", "ציפור", "דג"] },
        { id: 21, en: "Bird", he: "ציפור", options: ["דוב", "אריה", "ציפור", "נחש"] },
        { id: 78, en: "Fish", he: "דג", options: ["דג", "אריה", "חתול", "סוס"] },
        { id: 79, en: "Horse", he: "סוס", options: ["סוס", "חתול", "דג", "פרה"] },
        { id: 80, en: "Cow", he: "פרה", options: ["פרה", "הכבש", "סוס", "תנין"] },
        { id: 81, en: "Sheep", he: "הכבש", options: ["הכבש", "כלב", "חתול", "דג"] },
        { id: 82, en: "Rabbit", he: "ארנב", options: ["ארנב", "חמור", "סוס", "עורב"] },
        { id: 83, en: "Lion", he: "אריה", options: ["אריה", "נחש", "דג", "ציפור"] },
        { id: 84, en: "Elephant", he: "פיל", options: ["פיל", "עכבר", "סוס", "כלב"] },
      ]
    },
    {
      id: 7,
      title: "פירות",
      icon: "🍎",
      color: "bg-orange-400",
      totalQuestions: 10,
      words: [
        { id: 22, en: "Apple", he: "תפוח", options: ["אגס", "תפוח", "בננה", "ענב"] },
        { id: 23, en: "Banana", he: "בננה", options: ["בננה", "תפוח", "תות", "אשכולית"] },
        { id: 24, en: "Grape", he: "ענב", options: ["מלון", "ענב", "לימון", "דובדבן"] },
        { id: 85, en: "Orange", he: "תפוז", options: ["מלון", "תפוז", "אגס", "בננה"] },
        { id: 86, en: "Pear", he: "אגס", options: ["אגס", "תפוח", "אבטיח", "ענב"] },
        { id: 87, en: "Strawberry", he: "תות", options: ["תות", "מלון", "תפוח", "אפרסק"] },
        { id: 88, en: "Watermelon", he: "אבטיח", options: ["אבטיח", "לימון", "בננה", "ענב"] },
        { id: 89, en: "Peach", he: "אפרסק", options: ["אפרסק", "תפוח", "שזיף", "מלון"] },
        { id: 90, en: "Cherry", he: "דובדבן", options: ["דובדבן", "אגס", "אפרסק", "תות"] },
        { id: 91, en: "Lemon", he: "לימון", options: ["לימון", "תפוח", "בננה", "ענב"] },
      ]
    },
    {
      id: 8,
      title: "גוף",
      icon: "👶",
      color: "bg-pink-300",
      totalQuestions: 10,
      words: [
        { id: 25, en: "Hand", he: "יד", options: ["רגל", "יד", "ראש", "אוזן"] },
        { id: 26, en: "Head", he: "ראש", options: ["בטן", "לחי", "ראש", "שן"] },
        { id: 27, en: "Eye", he: "עין", options: ["פה", "אף", "עין", "שיער"] },
        { id: 92, en: "Ear", he: "אוזן", options: ["פה", "אוזן", "עין", "אף"] },
        { id: 93, en: "Nose", he: "אף", options: ["אף", "שן", "ראש", "יד"] },
        { id: 94, en: "Mouth", he: "פה", options: ["פה", "אוזן", "עין", "לב"] },
        { id: 95, en: "Leg", he: "רגל", options: ["יד", "רגל", "ראש", "בטן"] },
        { id: 96, en: "Finger", he: "אצבע", options: ["אצבע", "אגודל", "ברך", "קרסול"] },
        { id: 97, en: "Tooth", he: "שן", options: ["שן", "שיער", "אף", "עין"] },
        { id: 98, en: "Hair", he: "שיער", options: ["שיער", "עור", "רגל", "יד"] },
      ]
    },
    {
      id: 9,
      title: "בגדים",
      icon: "👕",
      color: "bg-blue-300",
      totalQuestions: 10,
      words: [
        { id: 28, en: "Shirt", he: "חולצה", options: ["מכנסיים", "חולצה", "מעיל", "חגורה"] },
        { id: 29, en: "Pants", he: "מכנסיים", options: ["חצאית", "מכנסיים", "גרביים", "נעליים"] },
        { id: 30, en: "Hat", he: "כובע", options: ["חגורה", "כובע", "כפפה", "צעיף"] },
        { id: 99, en: "Socks", he: "גרביים", options: ["כפפה", "גרביים", "כובע", "חולצה"] },
        { id: 100, en: "Shoes", he: "נעליים", options: ["נעליים", "כפפה", "סוודר", "שמלה"] },
        { id: 101, en: "Coat", he: "מעיל", options: ["חולצה", "מעיל", "מכנסיים", "כובע"] },
        { id: 102, en: "Dress", he: "שמלה", options: ["ג'ינס", "סוודר", "שטרו", "שמלה"] },
        { id: 103, en: "Belt", he: "חגורה", options: ["כפפה", "חגורה", "כובע", "נעל"] },
        { id: 104, en: "Gloves", he: "כפפות", options: ["מעיל", "כפפות", "כובע", "צעיף"] },
        { id: 105, en: "Scarf", he: "צעיף", options: ["כובע", "צעיף", "חגורה", "חולצה"] },
      ]
    },
    {
      id: 10,
      title: "צעצועים",
      icon: "🧸",
      color: "bg-purple-300",
      totalQuestions: 10,
      words: [
        { id: 31, en: "Doll", he: "בובה", options: ["כדור", "בובה", "חבל", "משולש"] },
        { id: 32, en: "Ball", he: "כדור", options: ["כדור", "ספר", "מכונית", "צעצוע"] },
        { id: 33, en: "Car", he: "מכונית", options: ["סוס", "מכונית", "מטוס", "סירה"] },
        { id: 124, en: "Puzzle", he: "פאזל", options: ["פאזל", "בובה", "כדור", "חבל"] },
        { id: 125, en: "Crayons", he: "צבעים", options: ["צבעים", "עפרונות", "דף", "מחברת"] },
        { id: 126, en: "Blocks", he: "קוביות", options: ["קוביות", "חבל", "בובה", "ספר"] },
        { id: 127, en: "Kite", he: "עפיפון", options: ["עפיפון", "כדור", "משאית", "בובה"] },
        { id: 128, en: "Yo-yo", he: "יו-יו", options: ["יו-יו", "כדור", "בובה", "מטוס"] },
        { id: 129, en: "Train set", he: "רכבת צעצוע", options: ["רכבת צעצוע", "מכונית", "בובה", "כדור"] },
        { id: 130, en: "Stuffed bear", he: "דובי ממולא", options: ["דובי", "רובוט", "בובה", "כדור"] },
      ]
    },
    {
      id: 11,
      title: "מזג אוויר",
      icon: "☀️",
      color: "bg-yellow-300",
      totalQuestions: 10,
      words: [
        { id: 34, en: "Sun", he: "שמש", options: ["ירח", "שמש", "גשם", "שלג"] },
        { id: 35, en: "Rain", he: "גשם", options: ["רוח", "גשם", "ברק", "ענן"] },
        { id: 36, en: "Snow", he: "שלג", options: ["שלג", "שמש", "גשם", "ערפל"] },
        { id: 131, en: "Cloud", he: "ענן", options: ["שמש", "ענן", "גשם", "שלג"] },
        { id: 132, en: "Wind", he: "רוח", options: ["שמש", "גשם", "רוח", "שלג"] },
        { id: 133, en: "Storm", he: "סערה", options: ["סערה", "ערפל", "גשם", "שמש"] },
        { id: 134, en: "Fog", he: "ערפל", options: ["ערפל", "שמש", "גשם", "רוח"] },
        { id: 135, en: "Thunder", he: "רעם", options: ["ברד", "רעם", "ענן", "שמש"] },
        { id: 136, en: "Hail", he: "ברד", options: ["גשם", "ברד", "שלג", "ערפל"] },
        { id: 137, en: "Temperature", he: "טמפרטורה", options: ["מהירות", "גובה", "טמפרטורה", "זמן"] },
      ]
    },
    {
      id: 12,
      title: "תחבורה",
      icon: "🚗",
      color: "bg-indigo-300",
      totalQuestions: 10,
      words: [
        { id: 37, en: "Car", he: "מכונית", options: ["אופניים", "מכונית", "אוטובוס", "סירה"] },
        { id: 38, en: "Bus", he: "אוטובוס", options: ["אוטו", "אופנוע", "אוטובוס", "מטוס"] },
        { id: 39, en: "Bike", he: "אופניים", options: ["רכבת", "סירה", "אופניים", "מכונית"] },
        { id: 138, en: "Train", he: "רכבת", options: ["רכבת", "מכונית", "אוטו", "אוטובוס"] },
        { id: 139, en: "Tram", he: "חשמלית", options: ["חשמלית", "אוטובוס", "מכונית", "אופניים"] },
        { id: 140, en: "Ship", he: "אוניה", options: ["אוניה", "סירה", "מטוס", "רכבת"] },
        { id: 141, en: "Plane", he: "מטוס", options: ["מטוס", "אוטובוס", "מכונית", "סירה"] },
        { id: 142, en: "Subway", he: "רכבת תחתית", options: ["אוטובוס", "מכונית", "רכבת תחתית", "אופניים"] },
        { id: 143, en: "Scooter", he: "קורקינט", options: ["קורקינט", "אופניים", "מכונית", "אוטובוס"] },
        { id: 144, en: "Truck", he: "משאית", options: ["משאית", "מכונית", "אוטובוס", "רכבת"] },
      ]
    },
    {
      id: 13,
      title: "רגשות",
      icon: "😊",
      color: "bg-pink-200",
      totalQuestions: 10,
      words: [
        { id: 40, en: "Happy", he: "שמח", options: ["עצוב", "כועס", "שמח", "מפוחד"] },
        { id: 41, en: "Sad", he: "עצוב", options: ["שמח", "עצוב", "רגוע", "נחמד"] },
        { id: 42, en: "Angry", he: "כועס", options: ["שקט", "כועס", "שמחה", "פוחד"] },
        { id: 145, en: "Calm", he: "רגוע", options: ["לחוץ", "רגוע", "שמחה", "כועס"] },
        { id: 146, en: "Surprised", he: "מופתע", options: ["משועמם", "מרוצה", "מופתע", "עצוב"] },
        { id: 147, en: "Bored", he: "משועמם", options: ["משועמם", "מרוצה", "שמח", "כועס"] },
        { id: 148, en: "Proud", he: "גאה", options: ["מביך", "גאה", "עצוב", "לחוץ"] },
        { id: 149, en: "Tired", he: "עייף", options: ["מרוצה", "עייף", "נרגש", "כועס"] },
        { id: 150, en: "Nervous", he: "לחוץ", options: ["רגוע", "לחוץ", "שמח", "עצוב"] },
        { id: 151, en: "Excited", he: "נרגש", options: ["משועמם", "נרגש", "עצוב", "עצבני"] },
      ]
    },
    {
      id: 14,
      title: "ימים",
      icon: "📅",
      color: "bg-green-200",
      totalQuestions: 10,
      words: [
        { id: 43, en: "Monday", he: "יום שני", options: ["יום ראשון", "יום שני", "יום שלישי", "שבת"] },
        { id: 44, en: "Friday", he: "יום שישי", options: ["יום חמישי", "יום שישי", "יום שבת", "יום ראשון"] },
        { id: 45, en: "Sunday", he: "יום ראשון", options: ["שבת", "שני", "יום ראשון", "חמישי"] },
        { id: 152, en: "Thursday", he: "יום חמישי", options: ["יום חמישי", "יום שישי", "יום שבת", "יום ראשון"] },
        { id: 153, en: "Tuesday", he: "יום שלישי", options: ["יום שני", "יום שלישי", "יום רביעי", "שבת"] },
        { id: 154, en: "Wednesday", he: "יום רביעי", options: ["יום חמישי", "יום רביעי", "יום שני", "יום ראשון"] },
        { id: 155, en: "Saturday", he: "שבת", options: ["שבת", "יום ראשון", "שי", "שני"] },
        { id: 156, en: "Today", he: "היום", options: ["אתמול", "היום", "מחר", "לפני"] },
        { id: 157, en: "Tomorrow", he: "מחר", options: ["אתמול", "היום", "מחר", "עכשיו"] },
        { id: 158, en: "Yesterday", he: "אתמול", options: ["מחר", "אתמול", "היום", "לפני"] },
      ]
    },
    {
      id: 15,
      title: "חודשים לועזיים",
      icon: "📆",
      color: "bg-blue-200",
      totalQuestions: 10,
      words: [
        { id: 46, en: "January", he: "ינואר", options: ["אוקטובר", "ינואר", "אפריל", "יולי"] },
        { id: 47, en: "May", he: "מאי", options: ["מאי", "פברואר", "נובמבר", "מרץ"] },
        { id: 48, en: "August", he: "אוגוסט", options: ["אוגוסט", "יוני", "ספטמבר", "דצמבר"] },
        { id: 159, en: "February", he: "פברואר", options: ["מרץ", "פברואר", "ינואר", "אפריל"] },
        { id: 160, en: "March", he: "מרץ", options: ["מרץ", "אפריל", "מאי", "יוני"] },
        { id: 161, en: "April", he: "אפריל", options: ["אפריל", "מרץ", "יוני", "יולי"] },
        { id: 162, en: "June", he: "יוני", options: ["יוני", "יולי", "אוגוסט", "ספטמבר"] },
        { id: 163, en: "September", he: "ספטמבר", options: ["אוגוסט", "ספטמבר", "אוקטובר", "נובמבר"] },
        { id: 164, en: "November", he: "נובמבר", options: ["אוקטובר", "נובמבר", "דצמבר", "ספטמבר"] },
        { id: 165, en: "December", he: "דצמבר", options: ["נובמבר", "דצמבר", "ינואר", "אוקטובר"] },
      ]
    },
    {
      id: 16,
      title: "בית ספר",
      icon: "🏫",
      color: "bg-indigo-200",
      totalQuestions: 10,
      words: [
        { id: 49, en: "Teacher", he: "מורה", options: ["תלמיד", "מורה", "ספר", "לוח"] },
        { id: 50, en: "Book", he: "ספר", options: ["כיסא", "שולחן", "ספר", "עט"] },
        { id: 51, en: "Desk", he: "שולחן", options: ["שולחן", "מחק", "מחשב", "חלון"] },
        { id: 166, en: "Student", he: "תלמיד", options: ["מורה", "תלמיד", "חבר", "אח"] },
        { id: 167, en: "Classroom", he: "כיתה", options: ["כיתה", "חצר", "ספריה", "חדר"] },
        { id: 168, en: "Homework", he: "שיעורי בית", options: ["מבחן", "שיעורי בית", "פרויקט", "חופשה"] },
        { id: 169, en: "Lesson", he: "שיעור", options: ["שיעור", "מבחן", "אימון", "שעת"] },
        { id: 170, en: "Library", he: "ספריה", options: ["ספריה", "כיתה", "מחשב", "חצר"] },
        { id: 171, en: "Exam", he: "מבחן", options: ["מבחן", "מזגן", "שיר", "חופשה"] },
        { id: 172, en: "Notebook", he: "מחברת", options: ["מחברת", "עפרון", "עט", "ספר"] },
      ]
    },
    {
      id: 17,
      title: "בית",
      icon: "🏠",
      color: "bg-yellow-200",
      totalQuestions: 11,
      words: [
        { id: 52, en: "Door", he: "דלת", options: ["חלון", "גג", "דלת", "מרפסת"] },
        { id: 53, en: "Window", he: "חלון", options: ["מיטה", "דלת", "חלון", "ספה"] },
        { id: 54, en: "Bed", he: "מיטה", options: ["שולחן", "מיטה", "דלת", "סיר"] },
        { id: 173, en: "Roof", he: "גג", options: ["ריצפה", "גג", "דלת", "חלון"] },
        { id: 174, en: "Kitchen", he: "מטבח", options: ["מטבח", "חדר", "חצר", "מרפסת"] },
        { id: 175, en: "Sofa", he: "ספה", options: ["מיטה", "ספה", "שולחן", "כיסא"] },
        { id: 176, en: "Bathroom", he: "חדר אמבטיה", options: ["חדר שינה", "חדר אמבטיה", "מטבח", "משרד"] },
        { id: 177, en: "Garden", he: "גינה", options: ["גינה", "חצר", "מרפסת", "חדר"] },
        { id: 178, en: "Balcony", he: "מרפסת", options: ["מרפסת", "גג", "חדר", "מרתף"] },
        { id: 179, en: "Stairs", he: "מדרגות", options: ["דלת", "מדרגות", "חלון", "גג"] },
        { id: 201, en: "Toilet", he: "שירותים", options: ["מקלחת", "מטבח", "חדר שינה", "שירותים"] },
      ]
    },
    {
      id: 18,
      title: "טבע",
      icon: "🌳",
      color: "bg-green-300",
      totalQuestions: 10,
      words: [
        { id: 55, en: "Tree", he: "עץ", options: ["פרח", "עץ", "אבן", "מים"] },
        { id: 56, en: "Flower", he: "פרח", options: ["אדמה", "פרח", "עשב", "סלע"] },
        { id: 57, en: "River", he: "נהר", options: ["אגם", "נהר", "ים", "שדה"] },
        { id: 180, en: "Mountain", he: "הר", options: ["צוק", "גבעה", "הר", "עמק"] },
        { id: 181, en: "Ocean", he: "אוקיינוס", options: ["נהר", "אוקיינוס", "אגם", "ים"] },
        { id: 182, en: "Beach", he: "חוף", options: ["חוף", "ים", "יער", "מדבר"] },
        { id: 183, en: "Forest", he: "יער", options: ["יער", "פארק", "חוף", "מדבר"] },
        { id: 184, en: "Field", he: "שדה", options: ["שדה", "יער", "גן", "חצר"] },
        { id: 185, en: "Grass", he: "דשא", options: ["עץ", "פרח", "דשא", "סלע"] },
        { id: 186, en: "Rock", he: "סלע", options: ["סלע", "עפר", "דשא", "עץ"] },
      ]
    },
    {
      id: 19,
      title: "פעולות",
      icon: "🏃",
      color: "bg-red-200",
      totalQuestions: 10,
      words: [
        { id: 58, en: "Run", he: "לרוץ", options: ["לשחק", "לשיר", "לרוץ", "לרקוד"] },
        { id: 59, en: "Eat", he: "לאכול", options: ["לשתות", "לאכול", "לישון", "ללמוד"] },
        { id: 60, en: "Sleep", he: "לישון", options: ["לרקוד", "לשיר", "לישון", "לרוץ"] },
        { id: 187, en: "Sing", he: "לשיר", options: ["לרקוד", "לשיר", "לרוץ", "לשחק"] },
        { id: 188, en: "Dance", he: "לרקוד", options: ["לשיר", "לרקוד", "לקרוא", "לכתוב"] },
        { id: 189, en: "Read", he: "לקרוא", options: ["לכתוב", "לקרוא", "ללמוד", "לשחק"] },
        { id: 190, en: "Write", he: "לכתוב", options: ["לרוץ", "לכתוב", "לשיר", "לרקוד"] },
        { id: 191, en: "Swim", he: "לשחות", options: ["לשחות", "לרוץ", "לשיר", "לצחוק"] },
        { id: 192, en: "Work", he: "לעבוד", options: ["לשחק", "לעבוד", "לישון", "לקרוא"] },
        { id: 193, en: "Play", he: "לשחק", options: ["לשחק", "לקרוא", "ללמוד", "לעבוד"] },
      ]
    },
    {
      id: 20,
      title: "ניגודים",
      icon: "⚖️",
      color: "bg-gray-200",
      totalQuestions: 10,
      words: [
        { id: 61, en: "Big", he: "גדול", options: ["קטן", "גדול", "מהיר", "איטי"] },
        { id: 62, en: "Small", he: "קטן", options: ["חזק", "קטן", "גבוה", "נמוך"] },
        { id: 63, en: "Fast", he: "מהיר", options: ["איטי", "חזק", "מהיר", "כבד"] },
        { id: 194, en: "High", he: "גבוה", options: ["נמוך", "גבוה", "מהיר", "כבד"] },
        { id: 195, en: "Low", he: "נמוך", options: ["גבוה", "נמוך", "חזק", "חלש"] },
        { id: 196, en: "Strong", he: "חזק", options: ["חלש", "חזק", "מהיר", "איטי"] },
        { id: 197, en: "Weak", he: "חלש", options: ["חזק", "חלש", "גבוה", "נמוך"] },
        { id: 198, en: "Hot", he: "חם", options: ["קר", "חם", "לח", "יבש"] },
        { id: 199, en: "Cold", he: "קר", options: ["חם", "קר", "נעים", "לח"] },
        { id: 200, en: "Light", he: "קל", options: ["כבד", "קל", "מהיר", "איטי"] },
      ]
    }
  ],

  readingMaterials: [
    // --- Work Category ---
    {
      id: "p_job_1",
      type: "passage",
      title: "Tell Me About Yourself",
      heTitle: "ספר לי על עצמך",
      level: "בינוני",
      category: "Work",
      content: [
        { w: "In", t: "ב" }, { w: "an", t: " " }, { w: "interview,", t: "ראיון," },
        { w: "this", t: "זו" }, { w: "is", t: "היא" }, { w: "a", t: " " },
        { w: "common", t: "שאלה נפוצה", phraseId: "common_question" },
        { w: "question.", t: "שאלה נפוצה", phraseId: "common_question" },
        { w: "You", t: "אתה" }, { w: "should", t: "צריך" },
        { w: "talk", t: "לדבר על", phraseId: "talk_about" },
        { w: "about", t: "לדבר על", phraseId: "talk_about" },
        { w: "your", t: "שלך" },
        { w: "experience", t: "ניסיון עבודה", phraseId: "work_exp" },
        { w: "and", t: "ו" }, { w: "skills.", t: "כישורים." },
        { w: "Keep", t: "שמור על זה", phraseId: "keep_it" },
        { w: "it", t: "שמור על זה", phraseId: "keep_it" },
        { w: "short", t: "קצר" }, { w: "and", t: "ו" }, { w: "professional.", t: "מקצועי." },
        { w: "I", t: "אני" }, { w: "graduated", t: "סיימתי לימודים" }, { w: "last", t: "שנה שעברה", phraseId: "last_year" }, { w: "year.", t: "שנה שעברה", phraseId: "last_year" },
        { w: "My", t: "שלי" }, { w: "passion", t: "תשוקה" }, { w: "is", t: "היא" }, { w: "building", t: "לבנות" }, { w: "software.", t: "תוכנה." }
      ]
    },
    {
      id: "p_job_2",
      type: "passage",
      title: "Coding Challenge",
      heTitle: "אתגר תכנות",
      level: "מתקדם",
      category: "Work",
      content: [
        { w: "The", t: "ה" }, { w: "interviewer", t: "מראיין" },
        { w: "asked", t: "ביקש ממני", phraseId: "asked_me" },
        { w: "me", t: "ביקש ממני", phraseId: "asked_me" },
        { w: "to", t: "ל" },
        { w: "solve", t: "לפתור בעיה", phraseId: "solve_prob" },
        { w: "a", t: "לפתור בעיה", phraseId: "solve_prob" },
        { w: "problem", t: "לפתור בעיה", phraseId: "solve_prob" },
        { w: "on", t: "על" }, { w: "the", t: "ה" }, { w: "whiteboard.", t: "לוח מחיק." },
        { w: "I", t: "אני" }, { w: "had", t: "הייתי צריך" }, { w: "to", t: "ל" },
        { w: "write", t: "לכתוב פונקציה", phraseId: "write_func" },
        { w: "a", t: "לכתוב פונקציה", phraseId: "write_func" },
        { w: "function", t: "לכתוב פונקציה", phraseId: "write_func" },
        { w: "in", t: "ב" }, { w: "Python.", t: "פייתון." },
        { w: "It", t: "זה" }, { w: "was", t: "היה" }, { w: "hard,", t: "קשה," }, { w: "but", t: "אבל" }, { w: "I", t: "אני" }, { w: "succeeded.", t: "הצלחתי." },
        { w: "I", t: "אני" }, { w: "tested", t: "בדקתי" }, { w: "the", t: "את" }, { w: "code", t: "הקוד" }, { w: "carefully.", t: "בזהירות." }
      ]
    },
    {
      id: "p_job_3",
      type: "passage",
      title: "Salary Expectations",
      heTitle: "ציפיות שכר",
      level: "מתקדם",
      category: "Work",
      content: [
        { w: "When", t: "כאשר" }, { w: "asked", t: "נשאלים" }, { w: "about", t: "לגבי" },
        { w: "salary", t: "ציפיות שכר", phraseId: "salary_exp" },
        { w: "expectations,", t: "ציפיות שכר", phraseId: "salary_exp" },
        { w: "it", t: "זה" }, { w: "is", t: "זה" }, { w: "important", t: "חשוב" }, { w: "to", t: "ל" },
        { w: "do", t: "לעשות מחקר", phraseId: "do_research" },
        { w: "research", t: "לעשות מחקר", phraseId: "do_research" },
        { w: "first.", t: "קודם." },
        { w: "Know", t: "דע" }, { w: "your", t: "שלך" }, { w: "worth", t: "שווי" }, { w: "in", t: "ב" }, { w: "the", t: "ה" }, { w: "market.", t: "שוק." },
        { w: "Also,", t: "כמו כן," }, { w: "consider", t: "שקול" }, { w: "the", t: "את" }, { w: "benefits.", t: "הטבות." },
        { w: "Be", t: "היה" }, { w: "confident", t: "בטוח בעצמך" }, { w: "when", t: "כש" }, { w: "you", t: "אתה" }, { w: "negotiate.", t: "מנהל מו״מ." }
      ]
    },
    {
      id: "p_job_4",
      type: "passage",
      title: "Team Work",
      heTitle: "עבודת צוות",
      level: "בינוני",
      category: "Work",
      content: [
        { w: "Companies", t: "חברות" }, { w: "look", t: "מחפשות", phraseId: "look_for" }, { w: "for", t: "מחפשות", phraseId: "look_for" },
        { w: "team", t: "שחקני קבוצה (אנשי צוות)", phraseId: "team_players" },
        { w: "players.", t: "שחקני קבוצה (אנשי צוות)", phraseId: "team_players" },
        { w: "They", t: "הם" }, { w: "want", t: "רוצים" }, { w: "someone", t: "מישהו" }, { w: "who", t: "ש" }, { w: "can", t: "יכול" },
        { w: "communicate", t: "לתקשר", phraseId: "communicate_well" },
        { w: "well", t: "היטב", phraseId: "communicate_well" },
        { w: "and", t: "ו" }, { w: "help", t: "לעזור" }, { w: "others.", t: "לאחרים." },
        { w: "Sharing", t: "שיתוף ידע", phraseId: "sharing_knowledge" },
        { w: "knowledge", t: "שיתוף ידע", phraseId: "sharing_knowledge" },
        { w: "is", t: "זה" }, { w: "vital.", t: "חיוני." }
      ]
    },
    {
      id: "p_job_5",
      type: "passage",
      title: "Remote Work",
      heTitle: "עבודה מרחוק",
      level: "בינוני",
      category: "Work",
      content: [
        { w: "Many", t: "הרבה" }, { w: "developers", t: "מפתחים" }, { w: "prefer", t: "מעדיפים" },
        { w: "remote", t: "עבודה מרחוק", phraseId: "remote_work" },
        { w: "work.", t: "עבודה מרחוק", phraseId: "remote_work" },
        { w: "It", t: "זה" }, { w: "saves", t: "חוסך" }, { w: "time", t: "זמן" }, { w: "on", t: "על" },
        { w: "commuting", t: "נסיעות לעבודה", phraseId: "commuting" },
        { w: "and", t: "ו" }, { w: "offers", t: "מציע" }, { w: "flexibility.", t: "גמישות." },
        { w: "I", t: "אני" }, { w: "have", t: "יש לי" }, { w: "a", t: "משרד ביתי", phraseId: "home_office" }, { w: "home", t: "משרד ביתי", phraseId: "home_office" }, { w: "office.", t: "משרד ביתי", phraseId: "home_office" },
        { w: "Good", t: "תקשורת טובה", phraseId: "good_comm" }, { w: "communication", t: "תקשורת טובה", phraseId: "good_comm" }, { w: "is", t: "היא" }, { w: "key.", t: "המפתח." }
      ]
    },
    {
      id: "p_job_why",
      type: "passage",
      title: "Why Here?",
      heTitle: "למה כאן?",
      level: "בינוני",
      category: "Work",
      content: [
        { w: "Why", t: "למה" }, { w: "do", t: "האם" }, { w: "you", t: "אתה" },
        { w: "want", t: "רוצה לעבוד", phraseId: "want_work" },
        { w: "to", t: "רוצה לעבוד", phraseId: "want_work" },
        { w: "work", t: "רוצה לעבוד", phraseId: "want_work" },
        { w: "here?", t: "כאן?" },
        { w: "I", t: "אני" }, { w: "admire", t: "מעריץ" }, { w: "your", t: "שלכם" },
        { w: "company's", t: "המשימה של החברה", phraseId: "comp_mission" },
        { w: "mission", t: "המשימה של החברה", phraseId: "comp_mission" },
        { w: "and", t: "ו" }, { w: "values.", t: "ערכים." },
        { w: "I", t: "אני" }, { w: "use", t: "משתמש ב" }, { w: "your", t: "שלכם" }, { w: "app", t: "אפליקציה" }, { w: "daily.", t: "מדי יום." }
      ]
    },
    {
      id: "p_job_weakness",
      type: "passage",
      title: "Greatest Weakness",
      heTitle: "חולשה הכי גדולה",
      level: "בינוני",
      category: "Work",
      content: [
        { w: "What", t: "מה" }, { w: "is", t: "היא" }, { w: "your", t: "שלך" },
        { w: "greatest", t: "החולשה הכי גדולה", phraseId: "great_weak" },
        { w: "weakness?", t: "החולשה הכי גדולה", phraseId: "great_weak" },
        { w: "Sometimes,", t: "לפעמים," }, { w: "I", t: "אני" },
        { w: "focus", t: "מתמקד יותר מדי", phraseId: "focus_too" },
        { w: "too", t: "מתמקד יותר מדי", phraseId: "focus_too" },
        { w: "much", t: "מתמקד יותר מדי", phraseId: "focus_too" },
        { w: "on", t: "על" }, { w: "small", t: "קטנים" }, { w: "details.", t: "פרטים." },
        { w: "However,", t: "למרות זאת," }, { w: "I", t: "אני" }, { w: "am", t: " " }, { w: "working", t: "עובד" }, { w: "on", t: "על" }, { w: "it.", t: "זה." }
      ]
    },
    {
      id: "p_job_conflict",
      type: "passage",
      title: "Handling Conflict",
      heTitle: "התמודדות עם קונפליקט",
      level: "מתקדם",
      category: "Work",
      content: [
        { w: "Tell", t: "ספר" }, { w: "me", t: "לי" }, { w: "about", t: "על" },
        { w: "a", t: " " }, { w: "time", t: "פעם" }, { w: "you", t: "שאתה" },
        { w: "had", t: "היה לך קונפליקט", phraseId: "had_conflict" },
        { w: "a", t: "היה לך קונפליקט", phraseId: "had_conflict" },
        { w: "conflict.", t: "היה לך קונפליקט", phraseId: "had_conflict" },
        { w: "I", t: "אני" }, { w: "listened", t: "הקשבתי" }, { w: "to", t: "ל" },
        { w: "my", t: "הקולגה שלי", phraseId: "my_colleague" },
        { w: "colleague's", t: "הקולגה שלי", phraseId: "my_colleague" },
        { w: "view", t: "דעה/השקפה" },
        { w: "and", t: "ו" }, { w: "we", t: "אנחנו" },
        { w: "found", t: "מצאנו פתרון", phraseId: "found_sol" },
        { w: "a", t: "מצאנו פתרון", phraseId: "found_sol" },
        { w: "solution.", t: "מצאנו פתרון", phraseId: "found_sol" },
        { w: "The", t: "ה" }, { w: "project", t: "פרויקט" }, { w: "was", t: "היה" }, { w: "a", t: "הצלחה", phraseId: "success" }, { w: "success.", t: "הצלחה", phraseId: "success" }
      ]
    },
    {
      id: "p_job_scrum",
      type: "passage",
      title: "Daily Stand-up",
      heTitle: "פגישת צוות יומית",
      level: "מתקדם",
      category: "Work",
      content: [
        { w: "Every", t: "כל" }, { w: "morning,", t: "בוקר," }, { w: "we", t: "אנחנו" },
        { w: "have", t: "עורכים פגישה", phraseId: "have_meet" },
        { w: "a", t: "עורכים פגישה", phraseId: "have_meet" },
        { w: "meeting.", t: "פגישה.", phraseId: "have_meet" },
        { w: "We", t: "אנחנו" },
        { w: "discuss", t: "דנים בהתקדמות", phraseId: "discuss_prog" },
        { w: "our", t: "דנים בהתקדמות", phraseId: "discuss_prog" },
        { w: "progress", t: "דנים בהתקדמות", phraseId: "discuss_prog" },
        { w: "and", t: "ו" },
        { w: "any", t: "כל בעיה", phraseId: "any_issues" },
        { w: "issues.", t: "כל בעיה", phraseId: "any_issues" },
        { w: "The", t: "ה" }, { w: "meeting", t: "פגישה" }, { w: "is", t: "היא" }, { w: "very", t: "מאוד" }, { w: "short.", t: "קצרה." }
      ]
    },
    {
      id: "p_job_goals",
      type: "passage",
      title: "Future Goals",
      heTitle: "מטרות לעתיד",
      level: "מתקדם",
      category: "Work",
      content: [
        { w: "Where", t: "איפה" }, { w: "do", t: "האם" }, { w: "you", t: "אתה" },
        { w: "see", t: "רואה את עצמך", phraseId: "see_yourself" },
        { w: "yourself", t: "רואה את עצמך", phraseId: "see_yourself" },
        { w: "in", t: "בעוד" }, { w: "five", t: "חמש" }, { w: "years?", t: "שנים?" },
        { w: "I", t: "אני" }, { w: "want", t: "רוצה" }, { w: "to", t: "ל" },
        { w: "lead", t: "להוביל צוות", phraseId: "lead_team" },
        { w: "a", t: "להוביל צוות", phraseId: "lead_team" },
        { w: "team", t: "להוביל צוות", phraseId: "lead_team" },
        { w: "of", t: "של" }, { w: "developers.", t: "מפתחים." },
        { w: "I", t: "אני" }, { w: "also", t: "גם" }, { w: "want", t: "רוצה" }, { w: "to", t: "ל" }, { w: "master", t: "לשלוט ב" }, { w: "React.", t: "ריאקט." }
      ]
    },
    {
      id: "p_job_deadline",
      type: "passage",
      title: "Tight Deadline",
      heTitle: "דדליין לחוץ",
      level: "בינוני",
      category: "Work",
      content: [
        { w: "The", t: "ה" }, { w: "project", t: "פרויקט" },
        { w: "deadline", t: "מועד הגשה (דדליין)", phraseId: "deadline" },
        { w: "is", t: "הוא" }, { w: "tomorrow.", t: "מחר." },
        { w: "We", t: "אנחנו" }, { w: "must", t: "חייבים" },
        { w: "work", t: "לעבוד מהר", phraseId: "work_fast" },
        { w: "fast", t: "לעבוד מהר", phraseId: "work_fast" },
        { w: "to", t: "כדי" }, { w: "finish.", t: "לסיים." },
        { w: "We", t: "אנחנו" }, { w: "ordered", t: "הזמנו" }, { w: "pizza", t: "פיצה" }, { w: "and", t: "ו" }, { w: "stayed", t: "נשארנו" }, { w: "late.", t: "מאוחר." }
      ]
    },

    // --- Social Category ---
    {
      id: "p_friends_1",
      type: "passage",
      title: "Weekend Plans",
      heTitle: "תוכניות לסופ\"ש",
      level: "קל",
      category: "Social",
      content: [
        { w: "Hey", t: "היי" }, { w: "Dan,", t: "דן," },
        { w: "what", t: "מה אתה עושה?", phraseId: "what_doing" },
        { w: "are", t: "מה אתה עושה?", phraseId: "what_doing" },
        { w: "you", t: "מה אתה עושה?", phraseId: "what_doing" },
        { w: "doing", t: "מה אתה עושה?", phraseId: "what_doing" },
        { w: "this", t: "הזה" }, { w: "weekend?", t: "סופ\"ש?" },
        { w: "I", t: "אני" }, { w: "am", t: " " },
        { w: "going", t: "הולך לים", phraseId: "going_beach" },
        { w: "to", t: "הולך לים", phraseId: "going_beach" },
        { w: "the", t: "הולך לים", phraseId: "going_beach" },
        { w: "beach.", t: "הולך לים", phraseId: "going_beach" },
        { w: "Do", t: "האם" }, { w: "you", t: "אתה" },
        { w: "want", t: "רוצה לבוא?", phraseId: "want_come" },
        { w: "to", t: "רוצה לבוא?", phraseId: "want_come" },
        { w: "come?", t: "רוצה לבוא?", phraseId: "want_come" },
        { w: "The", t: "מזג האוויר", phraseId: "weather" }, { w: "weather", t: "מזג האוויר", phraseId: "weather" }, { w: "will", t: "יהיה" }, { w: "be", t: "יהיה" }, { w: "sunny.", t: "שמשי." }
      ]
    },
    {
      id: "p_friends_2",
      type: "passage",
      title: "Movie Night",
      heTitle: "ערב סרט",
      level: "קל",
      category: "Social",
      content: [
        { w: "Let's", t: "בוא" },
        { w: "watch", t: "נצפה בסרט", phraseId: "watch_movie" },
        { w: "a", t: "נצפה בסרט", phraseId: "watch_movie" },
        { w: "movie", t: "נצפה בסרט", phraseId: "watch_movie" },
        { w: "tonight.", t: "הערב." },
        { w: "I", t: "אני" }, { w: "have", t: "יש לי" }, { w: "popcorn", t: "פופקורן" }, { w: "and", t: "ו" }, { w: "drinks.", t: "שתייה." },
        { w: "Which", t: "איזה" }, { w: "movie", t: "סרט" }, { w: "do", t: "האם" }, { w: "you", t: "אתה" }, { w: "prefer,", t: "מעדיף," },
        { w: "action", t: "אקשן או קומדיה?", phraseId: "act_or_com" },
        { w: "or", t: "אקשן או קומדיה?", phraseId: "act_or_com" },
        { w: "comedy?", t: "אקשן או קומדיה?", phraseId: "act_or_com" }
      ]
    },
    {
      id: "p_friends_3",
      type: "passage",
      title: "New Phone",
      heTitle: "טלפון חדש",
      level: "בינוני",
      category: "Social",
      content: [
        { w: "Look", t: "תראה" }, { w: "at", t: "את" }, { w: "my", t: "שלי" },
        { w: "new", t: "טלפון חדש", phraseId: "new_phone" },
        { w: "phone!", t: "טלפון חדש", phraseId: "new_phone" },
        { w: "It", t: "יש לו" }, { w: "has", t: "יש לו" },
        { w: "an", t: "מצלמה מדהימה", phraseId: "amazing_cam" },
        { w: "amazing", t: "מצלמה מדהימה", phraseId: "amazing_cam" },
        { w: "camera.", t: "מצלמה מדהימה", phraseId: "amazing_cam" },
        { w: "I", t: "אני" }, { w: "can", t: "יכול" },
        { w: "take", t: "לצלם תמונות", phraseId: "take_photos" },
        { w: "great", t: "נהדרות" },
        { w: "photos", t: "לצלם תמונות", phraseId: "take_photos" },
        { w: "now.", t: "עכשיו." },
        { w: "It", t: "הוא" }, { w: "was", t: "היה" }, { w: "very", t: "מאוד" }, { w: "expensive,", t: "יקר," }, { w: "but", t: "אבל" }, { w: "worth", t: "שווה" }, { w: "it.", t: "את זה." }
      ]
    },
    {
      id: "p_friends_4",
      type: "passage",
      title: "Running Late",
      heTitle: "מאחר",
      level: "בינוני",
      category: "Social",
      content: [
        { w: "Sorry,", t: "מצטער," }, { w: "I", t: "אני" }, { w: "am", t: " " },
        { w: "running", t: "מאחר", phraseId: "running_late" },
        { w: "late.", t: "מאחר", phraseId: "running_late" },
        { w: "The", t: "ה" },
        { w: "traffic", t: "התנועה (פקקים)", phraseId: "traffic" },
        { w: "is", t: "היא" }, { w: "terrible.", t: "נוראית." },
        { w: "Please", t: "בבקשה" },
        { w: "wait", t: "חכה לי", phraseId: "wait_for_me" },
        { w: "for", t: "חכה לי", phraseId: "wait_for_me" },
        { w: "me.", t: "חכה לי", phraseId: "wait_for_me" },
        { w: "I", t: "אני" }, { w: "will", t: "אני (עתיד)" }, { w: "be", t: "אהיה" }, { w: "there", t: "שם" }, { w: "in", t: "בעוד" }, { w: "ten", t: "עשר" }, { w: "minutes.", t: "דקות." }
      ]
    },
    {
      id: "p_social_concert",
      type: "passage",
      title: "Concert Tickets",
      heTitle: "כרטיסים להופעה",
      level: "קל",
      category: "Social",
      content: [
        { w: "I", t: "אני" }, { w: "bought", t: "קניתי" },
        { w: "tickets", t: "כרטיסים להופעה", phraseId: "concert_tix" },
        { w: "to", t: "כרטיסים להופעה", phraseId: "concert_tix" },
        { w: "the", t: "כרטיסים להופעה", phraseId: "concert_tix" },
        { w: "concert.", t: "כרטיסים להופעה", phraseId: "concert_tix" },
        { w: "My", t: "שלי" }, { w: "favorite", t: "אהובה" }, { w: "band", t: "להקה" },
        { w: "is", t: "היא" },
        { w: "playing", t: "מנגנת הערב", phraseId: "playing_tonight" },
        { w: "tonight.", t: "מנגנת הערב", phraseId: "playing_tonight" },
        { w: "The", t: "ה" }, { w: "venue", t: "אולם/מקום" }, { w: "is", t: "הוא" }, { w: "huge.", t: "ענק." },
        { w: "I", t: "אני" }, { w: "am", t: "אני" }, { w: "so", t: "כל כך" }, { w: "excited.", t: "מתרגש." }
      ]
    },
    {
      id: "p_social_pizza",
      type: "passage",
      title: "Ordering Food",
      heTitle: "מזמינים אוכל",
      level: "קל",
      category: "Social",
      content: [
        { w: "I", t: "אני" }, { w: "am", t: " " }, { w: "hungry.", t: "רעב." },
        { w: "Let's", t: "בוא" },
        { w: "order", t: "נזמין פיצה", phraseId: "order_pizza" },
        { w: "pizza.", t: "נזמין פיצה", phraseId: "order_pizza" },
        { w: "I", t: "אני" }, { w: "want", t: "רוצה" },
        { w: "extra", t: "תוספת גבינה", phraseId: "extra_cheese" },
        { w: "cheese", t: "תוספת גבינה", phraseId: "extra_cheese" },
        { w: "on", t: "על" }, { w: "mine.", t: "שלי." },
        { w: "Do", t: "האם" }, { w: "you", t: "אתה" }, { w: "want", t: "רוצה" }, { w: "soda?", t: "שתייה קלה?" },
        { w: "Delivery", t: "משלוח", phraseId: "delivery_time" }, { w: "takes", t: "לוקח", phraseId: "delivery_time" }, { w: "thirty", t: "שלושים", phraseId: "delivery_time" }, { w: "minutes.", t: "דקות.", phraseId: "delivery_time" }
      ]
    },
    {
      id: "p_social_hobbies",
      type: "passage",
      title: "Music Hobbies",
      heTitle: "תחביבי מוזיקה",
      level: "קל",
      category: "Social",
      content: [
        { w: "Do", t: "האם" }, { w: "you", t: "אתה" },
        { w: "play", t: "מנגן על כלי כלשהו?", phraseId: "play_inst" },
        { w: "any", t: "מנגן על כלי כלשהו?", phraseId: "play_inst" },
        { w: "instruments?", t: "מנגן על כלי כלשהו?", phraseId: "play_inst" },
        { w: "Yes,", t: "כן," }, { w: "I", t: "אני" },
        { w: "play", t: "מנגן בגיטרה", phraseId: "play_guitar" },
        { w: "the", t: "מנגן בגיטרה", phraseId: "play_guitar" },
        { w: "guitar.", t: "מנגן בגיטרה", phraseId: "play_guitar" },
        { w: "I", t: "אני" }, { w: "practice", t: "מתאמן" }, { w: "every", t: "כל" }, { w: "day.", t: "יום." },
        { w: "Music", t: "מוזיקה" }, { w: "relaxes", t: "מרגיעה" }, { w: "me.", t: "אותי." }
      ]
    },
    {
      id: "p_social_bad_date",
      type: "passage",
      title: "A Bad Date",
      heTitle: "דייט גרוע",
      level: "בינוני",
      category: "Social",
      content: [
        { w: "I", t: "אני" }, { w: "went", t: "הלכתי" }, { w: "on", t: "ל" },
        { w: "a", t: "דייט נורא", phraseId: "terrible_date" },
        { w: "terrible", t: "דייט נורא", phraseId: "terrible_date" },
        { w: "date.", t: "דייט נורא", phraseId: "terrible_date" },
        { w: "He", t: "הוא" },
        { w: "talked", t: "דיבר רק", phraseId: "talked_only" },
        { w: "only", t: "דיבר רק", phraseId: "talked_only" },
        { w: "about", t: "על" }, { w: "himself", t: "עצמו" },
        { w: "all", t: "כל" }, { w: "night.", t: "הערב." },
        { w: "I", t: "אני" }, { w: "said", t: "אמרתי" }, { w: "I", t: "שאני" }, { w: "was", t: "הייתי" }, { w: "tired.", t: "עייפה." },
        { w: "I", t: "אני" }, { w: "went", t: "הלכתי" }, { w: "home", t: "הביתה" }, { w: "early.", t: "מוקדם." }
      ]
    },
    {
      id: "p_social_moving",
      type: "passage",
      title: "Moving House",
      heTitle: "עוברים דירה",
      level: "בינוני",
      category: "Social",
      content: [
        { w: "I", t: "אני" }, { w: "am", t: " " },
        { w: "moving", t: "עובר ל...", phraseId: "moving_to" },
        { w: "to", t: "עובר ל...", phraseId: "moving_to" },
        { w: "a", t: "דירה חדשה", phraseId: "new_apt" },
        { w: "new", t: "דירה חדשה", phraseId: "new_apt" },
        { w: "apartment.", t: "דירה חדשה", phraseId: "new_apt" },
        { w: "Can", t: "יכול" }, { w: "you", t: "אתה" },
        { w: "help", t: "לעזור לי", phraseId: "help_me" },
        { w: "me", t: "לעזור לי", phraseId: "help_me" },
        { w: "with", t: "עם" }, { w: "the", t: "ה" }, { w: "boxes?", t: "קופסאות?" },
        { w: "The", t: "ה" }, { w: "sofa", t: "ספה" }, { w: "is", t: "היא" }, { w: "very", t: "מאוד" }, { w: "heavy.", t: "כבדה." },
        { w: "I", t: "אני" }, { w: "will", t: "אני (עתיד)" }, { w: "buy", t: "אקנה" }, { w: "you", t: "לך" }, { w: "lunch.", t: "ארוחת צהריים." }
      ]
    },
    {
      id: "p_social_gym",
      type: "passage",
      title: "Gym Buddy",
      heTitle: "שותף לאימון",
      level: "קל",
      category: "Social",
      content: [
        { w: "Do", t: "האם" }, { w: "you", t: "אתה" }, { w: "want", t: "רוצה" }, { w: "to", t: "ל" },
        { w: "go", t: "ללכת לחדר כושר", phraseId: "go_gym" },
        { w: "to", t: "ללכת לחדר כושר", phraseId: "go_gym" },
        { w: "the", t: "ללכת לחדר כושר", phraseId: "go_gym" },
        { w: "gym?", t: "ללכת לחדר כושר", phraseId: "go_gym" },
        { w: "I", t: "אני" }, { w: "need", t: "צריך" }, { w: "to", t: "ל" }, { w: "exercise.", t: "להתעמל." },
        { w: "We", t: "אנחנו" }, { w: "can", t: "יכולים" }, { w: "motivate", t: "להמריץ/לעודד" }, { w: "each", t: "זה את זה", phraseId: "each_other_g" }, { w: "other.", t: "זה את זה", phraseId: "each_other_g" },
        { w: "Let's", t: "בוא" }, { w: "meet", t: "ניפגש" }, { w: "at", t: "ב" }, { w: "six.", t: "שש." }
      ]
    },

    // --- Daily Life Category ---
    {
      id: "p101",
      type: "passage",
      title: "My Morning Routine",
      heTitle: "שגרת הבוקר שלי",
      level: "קל",
      category: "Daily Life",
      content: [
        { w: "Every", t: "כל" }, { w: "day,", t: "יום," },
        { w: "I", t: "אני" },
        { w: "wake", t: "מתעורר (ביטוי)", phraseId: "wake_up_1" },
        { w: "up", t: "מתעורר (ביטוי)", phraseId: "wake_up_1" },
        { w: "at", t: "ב" },
        { w: "seven", t: "השעה שבע", phraseId: "seven_oclock_1" },
        { w: "o'clock.", t: "השעה שבע", phraseId: "seven_oclock_1" },
        { w: "The", t: "ה" }, { w: "sun", t: "שמש" }, { w: "is", t: "היא/ישנה" }, { w: "usually", t: "בדרך כלל" }, { w: "bright.", t: "זורחת/בהירה." },
        { w: "I", t: "אני" }, { w: "eat", t: "אוכל" },
        { w: "breakfast", t: "ארוחת בוקר" },
        { w: "with", t: "עם" },
        { w: "my", t: "המשפחה שלי", phraseId: "my_family_1" },
        { w: "family.", t: "המשפחה שלי", phraseId: "my_family_1" },
        { w: "Then,", t: "אז," }, { w: "I", t: "אני" }, { w: "get", t: "מתלבש", phraseId: "get_dressed" }, { w: "dressed", t: "מתלבש", phraseId: "get_dressed" }, { w: "quickly.", t: "מהר." },
        { w: "My", t: "שלי" }, { w: "bus", t: "אוטובוס" }, { w: "arrives", t: "מגיע" }, { w: "at", t: "ב" }, { w: "eight.", t: "שמונה." }
      ]
    },
    {
      id: "p102",
      type: "passage",
      title: "The Little Dog",
      heTitle: "הכלב הקטן",
      level: "קל",
      category: "Animals",
      content: [
        { w: "This", t: "זה" }, { w: "is", t: "הוא/הינו" }, { w: "Max.", t: "מקס." },
        { w: "Max", t: "מקס" }, { w: "is", t: "הוא/הינו" },
        { w: "a", t: "כלב קטן", phraseId: "small_dog" },
        { w: "small", t: "כלב קטן", phraseId: "small_dog" },
        { w: "dog.", t: "כלב קטן", phraseId: "small_dog" },
        { w: "He", t: "הוא" }, { w: "likes", t: "אוהב" }, { w: "to", t: "ל" }, { w: "play", t: "לשחק" }, { w: "in", t: "ב" }, { w: "the", t: "ה" }, { w: "park.", t: "פארק." },
        { w: "He", t: "הוא" }, { w: "barks", t: "נובח על", phraseId: "barks_at" }, { w: "at", t: "נובח על", phraseId: "barks_at" }, { w: "the", t: "ה" }, { w: "mailman.", t: "דוור." },
        { w: "We", t: "אנחנו" }, { w: "walk", t: "מטיילים איתו", phraseId: "walk_him" }, { w: "him", t: "מטיילים איתו", phraseId: "walk_him" }, { w: "twice", t: "פעמיים" }, { w: "a", t: "ב" }, { w: "day.", t: "יום." }
      ]
    },
    {
      id: "p103",
      type: "passage",
      title: "My Blue Bike",
      heTitle: "האופניים הכחולים שלי",
      level: "קל",
      category: "Hobbies",
      content: [
        { w: "I", t: "אני" }, { w: "have", t: "יש לי" },
        { w: "a", t: "אופניים כחולים", phraseId: "blue_bike" },
        { w: "blue", t: "אופניים כחולים", phraseId: "blue_bike" },
        { w: "bike.", t: "אופניים כחולים", phraseId: "blue_bike" },
        { w: "I", t: "אני" },
        { w: "ride", t: "רוכב עליהם", phraseId: "ride_it" },
        { w: "it", t: "רוכב עליהם", phraseId: "ride_it" },
        { w: "in", t: "ב" }, { w: "the", t: "ה" }, { w: "park", t: "פארק" },
        { w: "after", t: "אחרי בית ספר", phraseId: "after_school" },
        { w: "school.", t: "אחרי בית ספר", phraseId: "after_school" },
        { w: "I", t: "אני" }, { w: "always", t: "תמיד" }, { w: "wear", t: "חובש" }, { w: "a", t: "קסדה", phraseId: "helmet" }, { w: "helmet.", t: "קסדה", phraseId: "helmet" },
        { w: "Safety", t: "בטיחות" }, { w: "is", t: "היא" }, { w: "important.", t: "חשובה." }
      ]
    },
    {
      id: "p_daily_doctor",
      type: "passage",
      title: "At the Doctor",
      heTitle: "אצל הרופא",
      level: "בינוני",
      category: "Daily Life",
      content: [
        { w: "I", t: "אני" }, { w: "have", t: "יש לי" },
        { w: "a", t: "כאב ראש", phraseId: "headache" },
        { w: "headache.", t: "כאב ראש", phraseId: "headache" },
        { w: "The", t: "ה" }, { w: "doctor", t: "רופא" },
        { w: "gave", t: "נתן לי", phraseId: "gave_me" },
        { w: "me", t: "נתן לי", phraseId: "gave_me" },
        { w: "medicine.", t: "תרופה." },
        { w: "I", t: "אני" }, { w: "feel", t: "מרגיש" }, { w: "better", t: "יותר טוב" }, { w: "now.", t: "עכשיו." },
        { w: "I", t: "אני" }, { w: "must", t: "חייב" }, { w: "rest", t: "לנוח" }, { w: "for", t: "במשך" }, { w: "two", t: "יומיים", phraseId: "two_days" }, { w: "days.", t: "יומיים", phraseId: "two_days" },
        { w: "I", t: "אני" }, { w: "hope", t: "מקווה" }, { w: "to", t: "ל" }, { w: "recover", t: "להחלים" }, { w: "soon.", t: "בקרוב." }
      ]
    },
    {
      id: "p_daily_lost",
      type: "passage",
      title: "Asking Directions",
      heTitle: "שואלים כיוונים",
      level: "קל",
      category: "Daily Life",
      content: [
        { w: "Excuse", t: "סליחה", phraseId: "excuse_me" },
        { w: "me,", t: "סליחה", phraseId: "excuse_me" },
        { w: "where", t: "איפה" }, { w: "is", t: "נמצאת" }, { w: "the", t: "ה" }, { w: "station?", t: "תחנה?" },
        { w: "Go", t: "לך" },
        { w: "straight", t: "ישר", phraseId: "go_straight" },
        { w: "and", t: "ו" },
        { w: "turn", t: "פנה שמאלה", phraseId: "turn_left" },
        { w: "left.", t: "פנה שמאלה", phraseId: "turn_left" },
        { w: "It", t: "זה" }, { w: "is", t: "נמצא" }, { w: "near", t: "ליד" }, { w: "the", t: "ה" }, { w: "bank.", t: "בנק." },
        { w: "You", t: "אתה" }, { w: "will", t: " " }, { w: "see", t: "תראה" }, { w: "a", t: "בניין אדום", phraseId: "red_build" }, { w: "red", t: "בניין אדום", phraseId: "red_build" }, { w: "building.", t: "בניין אדום", phraseId: "red_build" }
      ]
    },
    {
      id: "p_daily_clothes",
      type: "passage",
      title: "Buying a Shirt",
      heTitle: "קונים חולצה",
      level: "קל",
      category: "Daily Life",
      content: [
        { w: "This", t: "הזו" }, { w: "shirt", t: "חולצה" }, { w: "is", t: "היא" },
        { w: "too", t: "קטנה מדי", phraseId: "too_small" },
        { w: "small.", t: "קטנה מדי", phraseId: "too_small" },
        { w: "Do", t: "האם" }, { w: "you", t: "לכם" }, { w: "have", t: "יש" },
        { w: "a", t: "מידה גדולה יותר", phraseId: "bigger_size" },
        { w: "bigger", t: "מידה גדולה יותר", phraseId: "bigger_size" },
        { w: "size?", t: "מידה גדולה יותר", phraseId: "bigger_size" },
        { w: "The", t: "ה" }, { w: "blue", t: "כחולה" }, { w: "one", t: "אחת (חולצה)" }, { w: "is", t: "היא" }, { w: "nice.", t: "נחמדה." },
        { w: "Can", t: "אפשר" }, { w: "I", t: "אני" }, { w: "try", t: "למדוד אותה", phraseId: "try_it" }, { w: "it", t: "למדוד אותה", phraseId: "try_it" }, { w: "on?", t: "למדוד אותה", phraseId: "try_it" }
      ]
    },
    {
      id: "p_daily_weather",
      type: "passage",
      title: "Rainy Day",
      heTitle: "יום גשום",
      level: "קל",
      category: "Daily Life",
      content: [
        { w: "It", t: "זה" }, { w: "is", t: "הוא" },
        { w: "raining", t: "יורד גשם", phraseId: "raining" },
        { w: "outside.", t: "בחוץ." },
        { w: "Don't", t: "אל" }, { w: "forget", t: "תשכח" }, { w: "to", t: "ל" },
        { w: "take", t: "לקחת מטריה", phraseId: "take_umbrella" },
        { w: "an", t: "לקחת מטריה", phraseId: "take_umbrella" },
        { w: "umbrella.", t: "לקחת מטריה", phraseId: "take_umbrella" },
        { w: "Wear", t: "תלבש" }, { w: "your", t: "שלך" }, { w: "boots.", t: "מגפיים." },
        { w: "It", t: "זה" }, { w: "is", t: "הוא" }, { w: "cold", t: "קר" }, { w: "too.", t: "גם." }
      ]
    },
    {
      id: "p_daily_2",
      type: "passage",
      title: "Grocery Shopping",
      heTitle: "קניות בסופר",
      level: "קל",
      category: "Daily Life",
      content: [
        { w: "I", t: "אני" }, { w: "need", t: "צריך" }, { w: "to", t: "ל" }, { w: "buy", t: "לקנות" },
        { w: "milk", t: "חלב" }, { w: "and", t: "ו" }, { w: "eggs.", t: "ביצים." },
        { w: "The", t: "ה" }, { w: "supermarket", t: "סופרמרקט" }, { w: "is", t: "הוא" }, { w: "near", t: "קרוב ל..." }, { w: "my", t: "שלי" }, { w: "house.", t: "בית." },
        { w: "I", t: "אני" }, { w: "will", t: "אני (עתיד)" }, { w: "pay", t: "אשלם", phraseId: "pay_with" }, { w: "with", t: "עם/ב", phraseId: "pay_with" },
        { w: "cash.", t: "מזומן." },
        { w: "I", t: "אני" }, { w: "also", t: "גם" }, { w: "need", t: "צריך" }, { w: "bread.", t: "לחם." },
        { w: "The", t: "ה" }, { w: "line", t: "תור" }, { w: "is", t: "הוא" }, { w: "very", t: "מאוד" }, { w: "long.", t: "ארוך." }
      ]
    },
    {
      id: "p_daily_3",
      type: "passage",
      title: "Cooking Dinner",
      heTitle: "מכין ארוחת ערב",
      level: "בינוני",
      category: "Daily Life",
      content: [
        { w: "Tonight", t: "הערב" }, { w: "I", t: "אני" }, { w: "am", t: " " },
        { w: "cooking", t: "מבשל", phraseId: "cooking" },
        { w: "pasta.", t: "פסטה." },
        { w: "I", t: "אני" }, { w: "boil", t: "מרתיח את המים", phraseId: "boil_water" },
        { w: "the", t: "מרתיח את המים", phraseId: "boil_water" },
        { w: "water", t: "מרתיח את המים", phraseId: "boil_water" },
        { w: "and", t: "ו" }, { w: "chop", t: "קוצץ את הירקות", phraseId: "chop_veg" },
        { w: "the", t: "קוצץ את הירקות", phraseId: "chop_veg" },
        { w: "vegetables.", t: "קוצץ את הירקות", phraseId: "chop_veg" },
        { w: "I", t: "אני" }, { w: "add", t: "מוסיף" }, { w: "salt", t: "מלח" }, { w: "and", t: "ו" }, { w: "pepper.", t: "פלפל." },
        { w: "The", t: "ה" }, { w: "sauce", t: "רוטב" }, { w: "tastes", t: "יש לו טעם" }, { w: "amazing.", t: "מדהים." }
      ]
    },
    {
      id: "p_sci_1",
      type: "passage",
      title: "Black Holes",
      heTitle: "חורים שחורים",
      level: "מתקדם",
      category: "Science",
      content: [
        { w: "A", t: " " }, { w: "black", t: "חור שחור", phraseId: "black_hole" }, { w: "hole", t: "חור שחור", phraseId: "black_hole" },
        { w: "is", t: "הוא" }, { w: "a", t: " " },
        { w: "region", t: "אזור בחלל", phraseId: "region_space" },
        { w: "in", t: "אזור בחלל", phraseId: "region_space" },
        { w: "space", t: "אזור בחלל", phraseId: "region_space" },
        { w: "where", t: "איפה ש..." }, { w: "gravity", t: "כוח המשיכה" }, { w: "is", t: "הוא" },
        { w: "very", t: "מאוד חזק", phraseId: "very_strong" },
        { w: "strong.", t: "מאוד חזק", phraseId: "very_strong" },
        { w: "Nothing", t: "שום דבר" }, { w: "can", t: "יכול" }, { w: "escape", t: "לברוח" }, { w: "from", t: "מ..." }, { w: "it.", t: "ממנו." },
        { w: "They", t: "הם" }, { w: "are", t: "הינם" }, { w: "invisible.", t: "בלתי נראים." },
        { w: "Time", t: "זמן" }, { w: "slows", t: "מאט", phraseId: "slows_down" }, { w: "down", t: "מאט", phraseId: "slows_down" }, { w: "near", t: "ליד" }, { w: "them.", t: "הם." }
      ]
    },

    // --- Stories ---
    {
      id: "s101",
      type: "story",
      title: "The Magic Forest",
      heTitle: "היער הקסום",
      level: "קל",
      category: "Fantasy",
      content: [
        { w: "Once", t: "פעם אחת", phraseId: "once_upon" }, { w: "upon", t: "פעם אחת", phraseId: "once_upon" }, { w: "a", t: "פעם אחת", phraseId: "once_upon" }, { w: "time,", t: "זמן," },
        { w: "there", t: "היה" }, { w: "was", t: "היה" },
        { w: "a", t: "ילד קטן", phraseId: "little_boy" },
        { w: "little", t: "ילד קטן", phraseId: "little_boy" },
        { w: "boy", t: "ילד קטן", phraseId: "little_boy" },
        { w: "named", t: "בשם" }, { w: "Tom.", t: "תום." },
        { w: "He", t: "הוא" }, { w: "lived", t: "גר" }, { w: "near", t: "ליד" },
        { w: "a", t: "יער גדול", phraseId: "big_forest" },
        { w: "big", t: "יער גדול", phraseId: "big_forest" },
        { w: "forest.", t: "יער גדול", phraseId: "big_forest" },
        { w: "One", t: "יום אחד", phraseId: "one_day_s" }, { w: "day,", t: "יום אחד", phraseId: "one_day_s" },
        { w: "Tom", t: "תום" }, { w: "found", t: "מצא" },
        { w: "a", t: "מפתח זהב", phraseId: "gold_key" },
        { w: "gold", t: "מפתח זהב", phraseId: "gold_key" },
        { w: "key.", t: "מפתח זהב", phraseId: "gold_key" },
        { w: "He", t: "הוא" }, { w: "opened", t: "פתח" },
        { w: "a", t: "דלת סודית", phraseId: "secret_door" },
        { w: "secret", t: "דלת סודית", phraseId: "secret_door" },
        { w: "door", t: "דלת סודית", phraseId: "secret_door" },
        { w: "in", t: "ב" }, { w: "a", t: "עץ." }, { w: "tree.", t: "עץ." },
        { w: "Inside,", t: "בפנים," }, { w: "he", t: "הוא" }, { w: "saw", t: "ראה" }, { w: "fairies.", t: "פיות." },
        { w: "The", t: "ה" }, { w: "fairies", t: "פיות" }, { w: "gave", t: "נתנו" }, { w: "him", t: "לו" }, { w: "magic", t: "אבקת קסמים", phraseId: "magic_dust" }, { w: "dust.", t: "אבקת קסמים", phraseId: "magic_dust" },
        { w: "He", t: "הוא" }, { w: "could", t: "יכול היה" }, { w: "fly", t: "לעוף" }, { w: "now.", t: "עכשיו." }
      ]
    },
    {
      id: "s_job_1",
      type: "story",
      title: "My First Tech Interview",
      heTitle: "ראיון הטכנולוגיה הראשון שלי",
      level: "מתקדם",
      category: "Work",
      content: [
        { w: "I", t: "אני" }, { w: "was", t: "הייתי" },
        { w: "nervous", t: "לחוץ לגבי...", phraseId: "nervous_about" },
        { w: "about", t: "לחוץ לגבי...", phraseId: "nervous_about" },
        { w: "my", t: "שלי" },
        { w: "job", t: "ראיון עבודה", phraseId: "job_interview" },
        { w: "interview", t: "ראיון עבודה", phraseId: "job_interview" },
        { w: "at", t: "ב" }, { w: "Google.", t: "גוגל." },
        { w: "I", t: "אני" },
        { w: "prepared", t: "התכוננתי", phraseId: "prepared_for" },
        { w: "for", t: "התכוננתי", phraseId: "prepared_for" },
        { w: "weeks.", t: "שבועות." },
        { w: "The", t: "ה" }, { w: "interviewer", t: "מראיין" }, { w: "was", t: "היה" }, { w: "nice.", t: "נחמד." },
        { w: "He", t: "הוא" },
        { w: "asked", t: "שאל אותי על", phraseId: "asked_about" },
        { w: "me", t: "שאל אותי על", phraseId: "asked_about" },
        { w: "about", t: "שאל אותי על", phraseId: "asked_about" },
        { w: "my", t: "שלי" },
        { w: "previous", t: "פרויקטים קודמים", phraseId: "prev_projects" },
        { w: "projects.", t: "פרויקטים קודמים", phraseId: "prev_projects" },
        { w: "Then,", t: "אז," }, { w: "we", t: "אנחנו" },
        { w: "talked", t: "דיברנו על", phraseId: "talked_about" },
        { w: "about", t: "דיברנו על", phraseId: "talked_about" },
        { w: "React", t: "ריאקט" }, { w: "and", t: "ו" }, { w: "JavaScript.", t: "ג'אווה סקריפט." },
        { w: "I", t: "אני" }, { w: "asked", t: "שאלתי" }, { w: "about", t: "על" }, { w: "the", t: "ה" }, { w: "team", t: "תרבות צוות", phraseId: "team_culture" }, { w: "culture.", t: "תרבות צוות", phraseId: "team_culture" },
        { w: "They", t: "הם" }, { w: "seemed", t: "נראו" }, { w: "very", t: "מאוד" }, { w: "friendly.", t: "חברותיים." },
        { w: "In", t: "ב" }, { w: "the", t: "ה" }, { w: "end,", t: "סוף," },
        { w: "I", t: "אני" },
        { w: "felt", t: "הרגשתי בטוח בעצמי", phraseId: "felt_confident" },
        { w: "confident.", t: "הרגשתי בטוח בעצמי", phraseId: "felt_confident" }
      ]
    },
    {
      id: "s_job_2",
      type: "story",
      title: "The Production Bug",
      heTitle: "הבאג בפרודקשן",
      level: "מתקדם",
      category: "Work",
      content: [
        { w: "It", t: "זה" }, { w: "was", t: "היה" }, { w: "Friday", t: "יום שישי" }, { w: "afternoon.", t: "אחר הצהריים." },
        { w: "Suddenly,", t: "פתאום," }, { w: "the", t: "ה" }, { w: "server", t: "שרת" },
        { w: "crashed.", t: "קרס." },
        { w: "My", t: "שלי" }, { w: "boss", t: "בוס" }, { w: "was", t: "היה" }, { w: "worried.", t: "מודאג." },
        { w: "I", t: "אני" }, { w: "checked", t: "בדקתי את ה..." }, { w: "the", t: "ה" }, { w: "logs", t: "לוגים (יומני רישום)" },
        { w: "and", t: "ו" },
        { w: "found", t: "מצאתי את השגיאה", phraseId: "found_error" },
        { w: "the", t: "מצאתי את השגיאה", phraseId: "found_error" },
        { w: "error.", t: "מצאתי את השגיאה", phraseId: "found_error" },
        { w: "I", t: "אני" },
        { w: "fixed", t: "תיקנתי את זה", phraseId: "fixed_it" },
        { w: "it", t: "תיקנתי את זה", phraseId: "fixed_it" },
        { w: "quickly", t: "במהירות" }, { w: "and", t: "ו" },
        { w: "deployed", t: "העליתי גרסה (Deploy)", phraseId: "deployed" },
        { w: "the", t: "ה" }, { w: "code.", t: "קוד." },
        { w: "Everyone", t: "כולם" }, { w: "was", t: "היו" }, { w: "happy.", t: "שמחים." }
      ]
    },
    {
      id: "s_friends_1",
      type: "story",
      title: "Coffee with Sarah",
      heTitle: "קפה עם שרה",
      level: "בינוני",
      category: "Social",
      content: [
        { w: "Yesterday,", t: "אתמול," }, { w: "I", t: "אני" },
        { w: "met", t: "פגשתי את", phraseId: "met_sarah" },
        { w: "Sarah", t: "פגשתי את", phraseId: "met_sarah" },
        { w: "at", t: "ב" }, { w: "a", t: "בית קפה", phraseId: "cafe" }, { w: "cafe.", t: "בית קפה", phraseId: "cafe" },
        { w: "We", t: "אנחנו" },
        { w: "haven't", t: "לא התראינו", phraseId: "havent_seen" },
        { w: "seen", t: "לא התראינו", phraseId: "havent_seen" },
        { w: "each", t: "אחד את השנייה", phraseId: "each_other" },
        { w: "other", t: "אחד את השנייה", phraseId: "each_other" },
        { w: "for", t: "במשך" },
        { w: "a", t: "הרבה זמן", phraseId: "long_time" },
        { w: "long", t: "הרבה זמן", phraseId: "long_time" },
        { w: "time.", t: "הרבה זמן", phraseId: "long_time" },
        { w: "She", t: "היא" },
        { w: "told", t: "סיפרה לי", phraseId: "told_me" },
        { w: "me", t: "סיפרה לי", phraseId: "told_me" },
        { w: "about", t: "על" }, { w: "her", t: "שלה" },
        { w: "new", t: "עבודה חדשה", phraseId: "new_job" },
        { w: "job.", t: "עבודה חדשה", phraseId: "new_job" },
        { w: "We", t: "אנחנו" },
        { w: "laughed", t: "צחקנו הרבה", phraseId: "laughed_lot" },
        { w: "a", t: "צחקנו הרבה", phraseId: "laughed_lot" },
        { w: "lot.", t: "צחקנו הרבה", phraseId: "laughed_lot" },
        { w: "We", t: "אנחנו" }, { w: "planned", t: "תכננו" }, { w: "to", t: "ל" }, { w: "meet", t: "להיפגש" }, { w: "again.", t: "שוב." },
        { w: "It", t: "זה" }, { w: "was", t: "היה" },
        { w: "great", t: "נהדר", phraseId: "great_catchup" },
        { w: "to", t: "להתעדכן", phraseId: "great_catchup" },
        { w: "catch", t: "להתעדכן", phraseId: "great_catchup" },
        { w: "up.", t: "להתעדכן", phraseId: "great_catchup" }
      ]
    },
    {
      id: "s_friends_2",
      type: "story",
      title: "The Birthday Surprise",
      heTitle: "הפתעת יום ההולדת",
      level: "קל",
      category: "Social",
      content: [
        { w: "It", t: "זה" }, { w: "was", t: "היה" }, { w: "Dan's", t: "של דן" }, { w: "birthday.", t: "יום הולדת." },
        { w: "His", t: "שלו" }, { w: "friends", t: "חברים" }, { w: "planned", t: "תכננו" },
        { w: "a", t: "מסיבה", phraseId: "party" }, { w: "party.", t: "מסיבה", phraseId: "party" },
        { w: "They", t: "הם" }, { w: "bought", t: "קנו" }, { w: "a", t: "עוגה", phraseId: "cake" }, { w: "cake", t: "עוגה", phraseId: "cake" },
        { w: "and", t: "ו" }, { w: "hid", t: "התחבאו" }, { w: "in", t: "ב" }, { w: "his", t: "שלו" }, { w: "house.", t: "בית." },
        { w: "When", t: "כש" }, { w: "he", t: "הוא" }, { w: "opened", t: "פתח" }, { w: "the", t: "את ה" }, { w: "door,", t: "דלת," },
        { w: "everyone", t: "כולם" }, { w: "shouted,", t: "צעקו," },
        { w: "Surprise!", t: "הפתעה!" }
      ]
    },
    {
      id: "s201",
      type: "story",
      title: "Planning a Trip",
      heTitle: "מתכננים טיול",
      level: "בינוני",
      category: "Travel",
      content: [
        { w: "Next", t: "הבא" }, { w: "month,", t: "חודש," }, { w: "my", t: "שלי" }, { w: "friends", t: "חברים" }, { w: "and", t: "ו" }, { w: "I", t: "אני" },
        { w: "are", t: "מתכננים (הווה מתמשך)", phraseId: "are_planning" },
        { w: "planning", t: "מתכננים (הווה מתמשך)", phraseId: "are_planning" },
        { w: "a", t: "טיול ל...", phraseId: "trip_to" },
        { w: "trip", t: "טיול ל...", phraseId: "trip_to" },
        { w: "to", t: "טיול ל...", phraseId: "trip_to" },
        { w: "London.", t: "לונדון." },
        { w: "We", t: "אנחנו" }, { w: "want", t: "רוצים" }, { w: "to", t: "ל" }, { w: "see", t: "לראות" },
        { w: "Big", t: "ביג בן", phraseId: "big_ben" },
        { w: "Ben", t: "ביג בן", phraseId: "big_ben" },
        { w: "and", t: "ו" }, { w: "visit", t: "לבקר" }, { w: "many", t: "הרבה" }, { w: "museums.", t: "מוזיאונים." },
        { w: "We", t: "אנחנו" }, { w: "also", t: "גם" }, { w: "booked", t: "הזמנו" }, { w: "a", t: "מלון", phraseId: "hotel" }, { w: "hotel.", t: "מלון", phraseId: "hotel" },
        { w: "It", t: "הוא" }, { w: "is", t: "נמצא" }, { w: "near", t: "ליד" }, { w: "the", t: "ה" }, { w: "city", t: "מרכז העיר", phraseId: "city_center" }, { w: "center.", t: "מרכז העיר", phraseId: "city_center" },
        { w: "Yesterday,", t: "אתמול," }, { w: "we", t: "אנחנו" },
        { w: "bought", t: "קנינו את הכרטיסים", phraseId: "bought_tickets" },
        { w: "the", t: "קנינו את הכרטיסים", phraseId: "bought_tickets" },
        { w: "tickets", t: "קנינו את הכרטיסים", phraseId: "bought_tickets" },
        { w: "online.", t: "באינטרנט." }
      ]
    },
    {
      id: "s301",
      type: "story",
      title: "The Future of Space",
      heTitle: "עתיד החלל",
      level: "מתקדם",
      category: "Science",
      content: [
        { w: "Humans", t: "בני אדם" }, { w: "have", t: "כבר (פועל עזר)" }, { w: "always", t: "תמיד" },
        { w: "been", t: "היו מוקסמים", phraseId: "been_fascinated" },
        { w: "fascinated", t: "היו מוקסמים", phraseId: "been_fascinated" },
        { w: "by", t: "על ידי" }, { w: "the", t: "ה" }, { w: "stars.", t: "כוכבים." },
        { w: "In", t: "ב" }, { w: "the", t: "ה" },
        { w: "last", t: "מאה האחרונה", phraseId: "last_century" },
        { w: "century,", t: "מאה האחרונה", phraseId: "last_century" },
        { w: "we", t: "אנחנו" }, { w: "have", t: "כבר" },
        { w: "made", t: "עשינו התקדמות", phraseId: "made_progress" },
        { w: "great", t: "עצומה", phraseId: "great" },
        { w: "progress", t: "עשינו התקדמות", phraseId: "made_progress" },
        { w: "in", t: "ב" },
        { w: "space", t: "חקר החלל", phraseId: "space_exploration" },
        { w: "exploration.", t: "חקר החלל", phraseId: "space_exploration" },
        { w: "Scientists", t: "מדענים" }, { w: "believe", t: "מאמינים" }, { w: "that", t: "ש" },
        { w: "one", t: "יום אחד", phraseId: "one_day" },
        { w: "day,", t: "יום אחד", phraseId: "one_day" },
        { w: "people", t: "אנשים" }, { w: "might", t: "עלולים/עשויים" },
        { w: "live", t: "לחיות על מאדים", phraseId: "live_on_mars" },
        { w: "on", t: "לחיות על מאדים", phraseId: "live_on_mars" },
        { w: "Mars.", t: "לחיות על מאדים", phraseId: "live_on_mars" },
        { w: "Terraforming", t: "הארצה (הפיכה ראוי למגורים)" }, { w: "might", t: "עשויה" }, { w: "be", t: "להיות" }, { w: "possible.", t: "אפשרית." },
        { w: "It", t: "זה" }, { w: "will", t: "יקח" }, { w: "take", t: "יקח" }, { w: "many", t: "הרבה" }, { w: "years.", t: "שנים." }
      ]
    },
    {
      id: "s_social_trip",
      type: "story",
      title: "Weekend Getaway",
      heTitle: "חופשת סוף שבוע",
      level: "בינוני",
      category: "Social",
      content: [
        { w: "My", t: "שלי" }, { w: "friends", t: "חברים" }, { w: "and", t: "ו" }, { w: "I", t: "אני" },
        { w: "are", t: "נוהגים (נוסעים)", phraseId: "driving" },
        { w: "driving", t: "נוהגים (נוסעים)", phraseId: "driving" },
        { w: "to", t: "ל" }, { w: "the", t: "ה" }, { w: "north.", t: "צפון." },
        { w: "We", t: "אנחנו" },
        { w: "rented", t: "שכרנו בקתה", phraseId: "rented_cabin" },
        { w: "a", t: "שכרנו בקתה", phraseId: "rented_cabin" },
        { w: "cabin", t: "שכרנו בקתה", phraseId: "rented_cabin" },
        { w: "in", t: "ב" }, { w: "the", t: "ה" }, { w: "woods.", t: "יער." },
        { w: "We", t: "אנחנו" }, { w: "plan", t: "מתכננים" }, { w: "to", t: "ל" },
        { w: "hike", t: "לטייל ברגל", phraseId: "hike" },
        { w: "and", t: "ו" }, { w: "relax.", t: "להירגע." },
        { w: "We", t: "אנחנו" }, { w: "will", t: "נבשל" }, { w: "cook", t: "נבשל" }, { w: "outside.", t: "בחוץ." },
        { w: "The", t: "ה" }, { w: "stars", t: "כוכבים" }, { w: "are", t: "הם" }, { w: "beautiful", t: "יפים" }, { w: "there.", t: "שם." },
        { w: "I", t: "אני" }, { w: "brought", t: "הבאתי" }, { w: "my", t: "שלי" }, { w: "camera.", t: "מצלמה." }
      ]
    },
    {
      id: "s_daily_english",
      type: "story",
      title: "Learning English",
      heTitle: "לומד אנגלית",
      level: "קל",
      category: "Daily Life",
      content: [
        { w: "I", t: "אני" },
        { w: "practice", t: "מתרגל אנגלית", phraseId: "practice_eng" },
        { w: "English", t: "מתרגל אנגלית", phraseId: "practice_eng" },
        { w: "every", t: "כל" }, { w: "day.", t: "יום." },
        { w: "It", t: "זה" }, { w: "helps", t: "עוזר" }, { w: "me", t: "לי" },
        { w: "improve", t: "להשתפר", phraseId: "improve" },
        { w: "fast.", t: "מהר." },
        { w: "I", t: "אני" }, { w: "read", t: "קורא" }, { w: "books", t: "ספרים" }, { w: "and", t: "ו" },
        { w: "listen", t: "מקשיב ל", phraseId: "listen_to" },
        { w: "to", t: "מקשיב ל", phraseId: "listen_to" },
        { w: "music.", t: "מוזיקה." },
        { w: "I", t: "אני" }, { w: "watch", t: "צופה ב" }, { w: "movies", t: "סרטים" }, { w: "with", t: "עם" }, { w: "subtitles.", t: "כתוביות." },
        { w: "I", t: "אני" }, { w: "speak", t: "מדבר" }, { w: "with", t: "עם" }, { w: "tourists.", t: "תיירים." },
        { w: "It", t: "זה" }, { w: "gets", t: "נהיה" }, { w: "easier", t: "קל יותר" }, { w: "every", t: "כל" }, { w: "day.", t: "יום." }
      ]
    }
  ]
};

const ACHIEVEMENTS = [
  { id: 1, title: "צעד ראשון", desc: "סיימת את השיעור הראשון", icon: "🚀", unlocked: true },
  { id: 2, title: "אש בעיניים", desc: "הגעת לרצף של 3 ימים", icon: "🔥", unlocked: true },
  { id: 3, title: "תולעת ספרים", desc: "קראת 5 סיפורים", icon: "🐛", unlocked: false },
  { id: 4, title: "פוליגלוט", desc: "למדת 100 מילים חדשות", icon: "🗣️", unlocked: false },
];

const CHAT_SCENARIOS = [
  { id: 'tutor', title: 'מורה פרטי', icon: <GraduationCap size={16} />, prompt: "You are a helpful and patient English tutor." },
  { id: 'barista', title: 'בית קפה', icon: <Coffee size={16} />, prompt: "Act as a barista in a coffee shop in London. I am a customer. Ask me what I want to order." },
  { id: 'interview', title: 'ראיון עבודה', icon: <Briefcase size={16} />, prompt: "Act as a hiring manager interviewing me for a job. Ask me professional questions." },
  { id: 'airport', title: 'שדה תעופה', icon: <Plane size={16} />, prompt: "Act as an immigration officer at an airport. Ask me for my passport and purpose of visit." },
  { id: 'doctor', title: 'רופא', icon: <Stethoscope size={16} />, prompt: "Act as a doctor. I am a patient coming for a checkup. Ask me about my symptoms." }
];

export { MOCK_DB, ACHIEVEMENTS, CHAT_SCENARIOS };